DailyStandup.Web/Areas/User/Controllers/DashboardController.cs
using DailyStandup.Infrastructure.ApplicationController;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DailyStandup.Web.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class DashboardController : BaseController
    {
        public DashboardController()
        {

        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Chat()
        {
            return View();
        }
    }
}

DailyStandup.Web/Areas/User/Controllers/PeerController.cs
using DailyStandup.Entities.Models.User;
using DailyStandup.Infrastructure.ApplicationController;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DailyStandup.Web.Areas.User.Controllers
{
    [Area("user")]
    [Authorize]
    public class PeerController : BaseController
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public PeerController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _userManager.Users.OrderBy(m=>m.FirstName).ToListAsync());
        }
    }
}

DailyStandup.Web/Areas/User/Controllers/ProjectController.cs
using DailyStandup.Common.Enums;
using DailyStandup.Entities.Models;
using DailyStandup.Entities.ViewModels.Standup;
using DailyStandup.Infrastructure.ApplicationController;
using DailyStandup.Infrastructure.Interfaces.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DailyStandup.Web.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class ProjectController : BaseController
    {
        private readonly IProjectService _projectService;

        public ProjectController(IProjectService projectService)
        {
            _projectService = projectService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _projectService.GetAll());
        }

        public IActionResult Create()
        {
            return View(new ProjectViewModel { });
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProjectViewModel projectViewModel)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }

            DataResult result = await _projectService.Create(projectViewModel);

            if(result.Status == Status.Success)
            {
                return RedirectToAction(nameof(Index));
            }

            return Json(result);
        }

        public async Task<IActionResult> Detail(Guid id)
        {
            return View(await _projectService.GetById(id));
        }
    }
}

DailyStandup.Web/Areas/User/Controllers/StandupController.cs
using DailyStandup.Common.Enums;
using DailyStandup.Entities.Models;
using DailyStandup.Entities.ViewModels.Standup;
using DailyStandup.Infrastructure.ApplicationController;
using DailyStandup.Infrastructure.Interfaces.IServices;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DailyStandup.Web.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class StandupController : BaseController
    {
        private readonly IWorkService _workService;
        private readonly IObstacleService _obstacleService;
        private readonly IProjectService _projectService;
        public StandupController(
            IWorkService workService,
            IProjectService projectService,
            IObstacleService obstacleService
            )
        {
            _workService = workService;
            _obstacleService = obstacleService;
            _projectService = projectService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(WorkViewModel viewModel)
        {

            if (ModelState.IsValid)
            {
                await _workService.Create(viewModel);

                return View(viewModel);
            }
            
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddObstacle(ObstacleViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                var result = await _obstacleService.Create(viewModel);

                return Json(result);
            }

            return Json(new DataResult
            {
                Status = Status.Failed,
                Message = $"{ModelState.Values.SelectMany(m => m.Errors).Select(m=>m.ErrorMessage)}"
            });
        }

        public async Task<IActionResult> UpdateObstacle(ObstacleViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                var result = await _obstacleService.Update(viewModel);

                return Json(result);
            }

            return Json(new DataResult
            {
                Status = Status.Failed,
                Message = $"{ModelState.Values.SelectMany(m => m.Errors).Select(m => m.ErrorMessage)}"
            });
        }
    }
}

DailyStandup.Web/Areas/User/Views/Shared/_DashboardFooterPartial.cshtml
<div class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                Copyright © 2018 Concept. All rights reserved. Dashboard by <a href="https://colorlib.com/wp/">Colorlib</a>.
            </div>
            <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12 col-12">
                <div class="text-md-right footer-links d-none d-sm-block">
                    <a href="javascript: void(0);">About</a>
                    <a href="javascript: void(0);">Support</a>
                    <a href="javascript: void(0);">Contact Us</a>
                </div>
            </div>
        </div>
    </div>
</div>

DailyStandup.Web/Areas/User/Views/Shared/_DashboardHeaderPartial.cshtml
<div class="dashboard-header">
    <nav class="navbar navbar-expand-lg bg-white fixed-top">
        <a class="navbar-brand" href="#">
            Daily Standup
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse " id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto navbar-right-top">
                <li class="nav-item">
                    <div id="custom-search" class="top-search-bar">
                        <input class="form-control" type="text" placeholder="Search..">
                    </div>
                </li>
                <li class="nav-item dropdown notification">
                    <a class="nav-link nav-icons" href="#" id="navbarDropdownMenuLink1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-fw fa-bell"></i> <span class="indicator"></span></a>
                    <ul class="dropdown-menu dropdown-menu-right notification-dropdown">
                        <li>
                            <div class="notification-title"> Notification</div>
                            <div class="notification-list">
                                <div class="list-group">
                                    <a href="#" class="list-group-item list-group-item-action active">
                                        <div class="notification-info">
                                            <div class="notification-list-user-img"><img src="~/lib/concept-master/images/avatar-2.jpg" alt="" class="user-avatar-md rounded-circle"></div>
                                            <div class="notification-list-user-block">
                                                <span class="notification-list-user-name">Jeremy Rakestraw</span>accepted your invitation to join the team.
                                                <div class="notification-date">2 min ago</div>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#" class="list-group-item list-group-item-action">
                                        <div class="notification-info">
                                            <div class="notification-list-user-img"><img src="~/lib/concept-master/images/avatar-3.jpg" alt="" class="user-avatar-md rounded-circle"></div>
                                            <div class="notification-list-user-block">
                                                <span class="notification-list-user-name">John Abraham </span>is now following you
                                                <div class="notification-date">2 days ago</div>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#" class="list-group-item list-group-item-action">
                                        <div class="notification-info">
                                            <div class="notification-list-user-img"><img src="~/lib/concept-master/images/avatar-4.jpg" alt="" class="user-avatar-md rounded-circle"></div>
                                            <div class="notification-list-user-block">
                                                <span class="notification-list-user-name">Monaan Pechi</span> is watching your main repository
                                                <div class="notification-date">2 min ago</div>
                                            </div>
                                        </div>
                                    </a>
                                    <a href="#" class="list-group-item list-group-item-action">
                                        <div class="notification-info">
                                            <div class="notification-list-user-img"><img src="~/lib/concept-master/images/avatar-5.jpg" alt="" class="user-avatar-md rounded-circle"></div>
                                            <div class="notification-list-user-block">
                                                <span class="notification-list-user-name">Jessica Caruso</span>accepted your invitation to join the team.
                                                <div class="notification-date">2 min ago</div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="list-footer"> <a href="#">View all notifications</a></div>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown connection">
                    <a class="nav-link" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="fas fa-fw fa-th"></i> </a>
                    <ul class="dropdown-menu dropdown-menu-right connection-dropdown">
                        <li class="connection-list">
                            <div class="row">
                                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12 ">
                                    <a href="#" class="connection-item"><img src="~/lib/concept-master/images/github.png" alt=""> <span>Github</span></a>
                                </div>
                                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12 ">
                                    <a href="#" class="connection-item"><img src="~/lib/concept-master/images/dribbble.png" alt=""> <span>Dribbble</span></a>
                                </div>
                                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12 ">
                                    <a href="#" class="connection-item"><img src="~/lib/concept-master/images/dropbox.png" alt=""> <span>Dropbox</span></a>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12 ">
                                    <a href="#" class="connection-item"><img src="~/lib/concept-master/images/bitbucket.png" alt=""> <span>Bitbucket</span></a>
                                </div>
                                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12 ">
                                    <a href="#" class="connection-item"><img src="~/lib/concept-master/images/mail_chimp.png" alt=""><span>Mail chimp</span></a>
                                </div>
                                <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12 ">
                                    <a href="#" class="connection-item"><img src="~/lib/concept-master/images/slack.png" alt=""> <span>Slack</span></a>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="conntection-footer"><a href="#">More</a></div>
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown nav-user">
                    <a class="nav-link nav-user-img" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img src="~/lib/concept-master/images/avatar-1.jpg" alt="" class="user-avatar-md rounded-circle"></a>
                    <div class="dropdown-menu dropdown-menu-right nav-user-dropdown" aria-labelledby="navbarDropdownMenuLink2">
                        <div class="nav-user-info">
                            <h5 class="mb-0 text-white nav-user-name">Mahesh Sunuwar</h5>
                            <span class="status"></span><span class="ml-2">Available</span>
                        </div>
                        <a class="dropdown-item" href="#"><i class="fas fa-user mr-2"></i>Account</a>
                        <a class="dropdown-item" asp-controller="Manage" asp-action="Index"><i class="fas fa-cog mr-2"></i>Setting</a>
                        <form asp-area="user" asp-controller="account" asp-action="logout">
                            <button class="dropdown-item" type="submit"><i class="fas fa-power-off mr-2"></i>Logout</button>
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</div>

DailyStandup.Web/Areas/User/Views/Shared/_DashboardLayout.cshtml
@{
    ViewData["Title"] = $"{ViewContext.RouteData.Values["action"]} {ViewContext.RouteData.Values["controller"]}";
}
<!doctype html>
<html lang="en">


<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"] - Daily Standup</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/lib/concept-master/vendor/bootstrap/css/bootstrap.min.css">
    <link href="~/lib/concept-master/vendor/fonts/circular-std/style.css" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/concept-master/libs/css/style.css">
    <link rel="stylesheet" href="~/lib/concept-master/vendor/fonts/fontawesome/css/fontawesome-all.css">

    <!-- libraries -->
    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />
    <link href="~/css/site.css" rel="stylesheet" />

    <!--page css-->
    @RenderSection("Css", required: false)
</head>

<body>
    <div class="dashboard-main-wrapper">
        @Html.Partial("_DashboardHeaderPartial")
        @Html.Partial("_DashboardSidebarPartial")
        <div class="dashboard-wrapper">
            <div class="influence-profile">
                <div class="container-fluid dashboard-content ">
                    <div class="row">
                        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                            <div class="page-header">
                                <h3 class="mb-2">@ViewData["Title"]</h3>
                                <div class="page-breadcrumb">
                                    <nav aria-label="breadcrumb">
                                        <ol class="breadcrumb">
                                            <li class="breadcrumb-item">
                                                <a href="#" class="breadcrumb-link">
                                                    @ViewContext.RouteData.Values["controller"]
                                                </a>
                                            </li>
                                        </ol>
                                    </nav>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!-- content -->
                    @RenderBody()
                </div>
            </div>
            <!-- ============================================================== -->
            <!-- end content -->
            <!-- ============================================================== -->
            @*@Html.Partial("_DashboardFooterPartial")*@
            <!-- ============================================================== -->
            <!-- end footer -->
            <!-- ============================================================== -->
        </div>
        <!-- ============================================================== -->
        <!-- end wrapper -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- end main wrapper -->
    <!-- ============================================================== -->
    <!-- Optional JavaScript -->
    <!-- jquery 3.3.1  -->
    <script src="~/lib/concept-master/vendor/jquery/jquery-3.3.1.min.js"></script>

    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <!-- bootstap bundle js -->
    <script src="~/lib/concept-master/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <!-- slimscroll js -->
    <script src="~/lib/concept-master/vendor/slimscroll/jquery.slimscroll.js"></script>
    <script src="~/lib/unobtrusive-ajax/unobtrusive-ajax.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>
    <!-- main js -->
    <script src="~/lib/concept-master/libs/js/main-js.js"></script>
    <script src="~/js/GlobalFunction.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>

DailyStandup.Web/Areas/User/Views/Shared/_DashboardSidebarPartial.cshtml
<div class="nav-left-sidebar sidebar-dark">
    <div class="menu-list">
        <nav class="navbar navbar-expand-lg navbar-light">
            <a class="d-xl-none d-lg-none" href="#">Dashboard</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav flex-column">
                    <li class="nav-divider">
                        Menu
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" asp-controller="Dashboard" asp-action="Index"><i class="fa fa-fw fa-user-circle"></i>Dashboard</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" asp-controller="Peer" asp-action="Index"><i class="fa fa-fw fa-user-circle"></i>Peer</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" asp-controller="Project" asp-action="Index"><i class="fa fa-fw fa-user-circle"></i>Projects</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" asp-controller="Standup" asp-action="Index"><i class="fa fa-fw fa-anchor"></i>Standup</a>
                    </li>
                    @*<li class="nav-hr-line">

                    </li>*@
                    <li class="nav-divider">
                        Groups
                    </li>
                    <!--list of group -->
                    <li class="nav-item">
                        <a href="#" class="nav-link">#General</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">#Dotnet</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">#Java</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">#AI</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

DailyStandup.Web/Areas/User/Views/Shared/_LoginLayout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewData["Title"] - DailyStandup</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="~/lib/srtdash/images/icon/favicon.ico">
    <link rel="stylesheet" href="~/lib/srtdash/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/lib/srtdash/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/lib/srtdash/css/themify-icons.css">
    <link rel="stylesheet" href="~/lib/srtdash/css/metisMenu.css">
    <link rel="stylesheet" href="~/lib/srtdash/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/lib/srtdash/css/slicknav.min.css">
    <link href="~/lib/toastr/toastr.min.css" rel="stylesheet" />
    <!-- amchart css -->
    <link rel="stylesheet" href="https://www.amcharts.com/lib/3/plugins/export/export.css" type="text/css" media="all" />
    <!-- others css -->
    <link rel="stylesheet" href="~/lib/srtdash/css/typography.css">
    <link rel="stylesheet" href="~/lib/srtdash/css/default-css.css">
    <link rel="stylesheet" href="~/lib/srtdash/css/styles.css">
    <link rel="stylesheet" href="~/lib/srtdash/css/responsive.css">
    <!-- modernizr css -->
    <script src="~/lib/srtdash/js/vendor/modernizr-2.8.3.min.js"></script>
</head>

<body>
    <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    <!-- preloader area start -->
    <div id="preloader">
        <div class="loader"></div>
    </div>
    <!-- preloader area end -->
    <!-- login area start -->
    <div class="login-area">
        <div class="container">
            <div class="login-box ptb--100">
                @RenderBody()
            </div>
        </div>
    </div>
    <!-- login area end -->
    <!-- jquery latest version -->
    <script src="~/lib/srtdash/js/vendor/jquery-2.2.4.min.js"></script>
    <!-- bootstrap 4 js -->
    <script src="~/lib/srtdash/js/popper.min.js"></script>
    <script src="~/lib/srtdash/js/bootstrap.min.js"></script>
    <script src="~/lib/srtdash/js/owl.carousel.min.js"></script>
    <script src="~/lib/srtdash/js/metisMenu.min.js"></script>
    <script src="~/lib/srtdash/js/jquery.slimscroll.min.js"></script>
    <script src="~/lib/srtdash/js/jquery.slicknav.min.js"></script>
    <script src="~/lib/unobtrusive-ajax/unobtrusive-ajax.min.js"></script>
    <script src="~/lib/toastr/toastr.min.js"></script>

    <!-- others plugins -->
    <script src="~/lib/srtdash/js/plugins.js"></script>
    <script src="~/lib/srtdash/js/scripts.js"></script>
    <script src="~/js/GlobalFunction.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>